version: '3.3'

services:

  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["-m", "mongo:27017:aussinator"]
    ports:
      - 127.0.0.1:9000:9000
    restart: unless-stopped
    depends_on:
      - mongo

